export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const UNDELETE_TODO = "UNDELETE_TODO";
export const MODIFY_TODO = "MODIFY_TODO";
export const SET_MESSAGE = "SET_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const MODIFY_CATEGORY = "MODIFY_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CHANGE_CATEGORY_NAME = "CHANGE_CATEGORY_NAME";


export const visibilityFilter = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_ACTIVE: "SHOW_ACTIVE",
  SHOW_DELETED: "SHOW_DELETED"
};
